version: '3.1'

services:
  db:
    build: db/
    hostname: db
    environment:
        MYSQL_ROOT_PASSWORD: iPJpIi63#15&pAZ@  # Change this!!
        MYSQL_DATABASE: MeDict
        MYSQL_USER: mysql
        MYSQL_PASSWORD: FH8tohUcr$P@OQsB       # Change this!!
        MYSQL_FLASK_USER: flask
        MYSQL_FLASK_PASSWORD: Ar1AaDH^xYBSrOs3 # Change this!!
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  backend:
    build: backend/
    container_name: backend
    hostname: backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - db
  frontend:
    build: frontend/
    hostname: frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - backend
networks:
  mynetwork:
    name: medict
    driver: bridge
    ipam:
      driver: default
