# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: khoi_test

    - name: Install dependencies
      run: |
        pip install flask_restful
        pip install flask
        pip install sqlalchemy
        pip instal gtts

    - name: Run tests
      run: |
        # Run your test command here. For example:
        python backend/test.py


